INSERT INTO ITEM (ETIQUETA, DESCRICAO, DATA_AQUISICAO) VALUES ('NT0123', 'Notebook 17', sysdate());
INSERT INTO ITEM (ETIQUETA, DESCRICAO, DATA_AQUISICAO) VALUES ('AU9875', 'Ford Fiesta', sysdate());
